SELECT LAT 
FROM
(SELECT CAST(ROUND(LAT_N, 4) AS DECIMAL(10, 4)) AS LAT, ROW_NUMBER() OVER(ORDER BY LAT_N) AS row_number FROM STATION) AS RANKING 
WHERE row_number IN 
(SELECT (COUNT(LAT_N)/2) + 1 FROM STATION);
